[MQTT]
host = 100.76.244.21
port = 10002
username = node
password = yQKcpr0PXnZHiPjzJw1Xd2B9RBFh5Pz67xAk6aks4x7xYTf3NRjaKKzxYaREkD5n
; Supports multiple topics, separated by commas, semicolons, or new lines
topic_filter =

[MYSQL]
host = 100.76.244.21
port = 3306
user = root
password = gdnx@2025
database = ems

[TDENGINE]
host = 100.76.244.21
port = 6041
username = root
password = taosdata
; TDengine目标数据库名称，不存在时程序启动会自动创建
database = ems
origin_stable_name = origin
day_stable_name = day
month_stable_name = month
subtable_prefix = d_

[REDIS]
url = redis://100.76.244.21:6379

[ENERGY_TYPE_CACHE]
ttl_seconds = 600
miss_ttl_seconds = 30
